name: Run unit tests on Ubuntu

on:
    push:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 5
            matrix:
                python-version: [3.11, 3.12, 3.13]  # Specify the Python versions you want to test against

        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install the project
              run: |
                  pip install --upgrade pip
                  pip install -e .[dev]
            
            - name: Run tests
              run: pytest
