name: Update CITATION.cff

on:
  push:
    branches:
      - main
      - master

jobs:
  update-citation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install toml ruamel.yaml

      - name: Run update_citation.py
        run: python scripts/update_citation.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add CITATION.cff
            git commit -m "chore: sync CITATION.cff version with pyproject.toml"
            git push
          else
            echo "No changes to commit."
          fi
